title: 90 Day Challenge
name: 90 Challenge
description: Tips and Tricks to get you through the 90 day challenge
relative_permalinks: true

# Your disqus shortname, entering this will enable commenting on posts
disqus: 

baseurl: ""
markdown: kramdown
highlighter: pygments
permalink: /:title/
version: v1.0.0
exclude:
    - LICENSE
    - README.md
    - localinfo.md
